services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_server
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: miapp
      ports: '27017:27017'
      volumes: ./mongo_data:/data/db